name = "IBMQClient"
uuid = "02860bad-daa6-4506-8736-4a3616c18085"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.3.2"

[deps]
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ConfParser = "0.1"
Configurations = "0.15"
Crayons = "4"
HTTP = "0.9"
JSON = "0.21"
URIs = "1"
julia = "1.6"

[extras]

[targets]
